### ISSUE TITLE
Curtain - Bluetooth command failed (code: 2, error: Attribute can't be read)

### ISSUE THREAD

**Issue by pascalwinters** [Danielhiversen/pySwitchbot#41] opened 2022-02-26 17:39 UTC
I have installed a new pair of Switchbot curtains.
With my existing curtains I have no problem, but with the new ones I receive failed commands.

Existing curtain firmware v3.1
New curtain firmware v3.3

I have added the full HomeAssistant log for issue tracking:
```
2022-02-26 18:30:55 DEBUG (SyncWorker_0) [switchbot] Sending command to switchbot <curtainid>
2022-02-26 18:30:55 DEBUG (SyncWorker_0) [switchbot] Connecting to Switchbot
2022-02-26 18:30:55 WARNING (SyncWorker_0) [switchbot] Bluepy busy, waiting before retry
2022-02-26 18:31:00 DEBUG (SyncWorker_0) [switchbot] Connecting to Switchbot
2022-02-26 18:31:01 WARNING (SyncWorker_0) [switchbot] Bluepy busy, waiting before retry
2022-02-26 18:31:06 DEBUG (SyncWorker_0) [switchbot] Connecting to Switchbot
2022-02-26 18:31:07 WARNING (SyncWorker_0) [switchbot] Bluepy busy, waiting before retry
2022-02-26 18:31:12 DEBUG (SyncWorker_0) [switchbot] Connecting to Switchbot
2022-02-26 18:31:12 WARNING (SyncWorker_0) [switchbot] Error connecting to Switchbot
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/switchbot/__init__.py", line 406, in _sendcommand
    self._connect(retry, timeout)
  File "/usr/local/lib/python3.9/site-packages/switchbot/__init__.py", line 294, in _connect
    return self._connect(retry - 1, timeout)
  File "/usr/local/lib/python3.9/site-packages/switchbot/__init__.py", line 294, in _connect
    return self._connect(retry - 1, timeout)
  File "/usr/local/lib/python3.9/site-packages/switchbot/__init__.py", line 294, in _connect
    return self._connect(retry - 1, timeout)
  File "/usr/local/lib/python3.9/site-packages/switchbot/__init__.py", line 271, in _connect
    raise bluepy.btle.BTLEDisconnectError(
bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral <mac>
2022-02-26 18:31:12 WARNING (SyncWorker_0) [switchbot] Cannot connect to Switchbot. Retrying (remaining: 3)
2022-02-26 18:31:17 DEBUG (SyncWorker_0) [switchbot] Sending command to switchbot <curtainid>
2022-02-26 18:31:17 DEBUG (SyncWorker_0) [switchbot] Connecting to Switchbot
2022-02-26 18:31:17 DEBUG (SyncWorker_0) [switchbot] Subscribe to notifications
2022-02-26 18:31:18 DEBUG (SyncWorker_0) [switchbot] Prepare to send
2022-02-26 18:31:18 DEBUG (SyncWorker_0) [switchbot] Sending command, <curtainid>
2022-02-26 18:31:18 INFO (SyncWorker_0) [switchbot] Successfully sent command to Switchbot (MAC: <mac>)
2022-02-26 18:31:18 DEBUG (SyncWorker_0) [switchbot] Prepare to read notification from switchbot
2022-02-26 18:31:19 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall cover.open_cover (c:a2ae2a5c023cfae9925c9f87ce61f786): entity_id=['cover.keuken']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1648, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1667, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 668, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 705, in _handle_entity_call
    await result
  File "/config/custom_components/switchbot/cover.py", line 101, in async_open_cover
    await self.hass.async_add_executor_job(self._device.open)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/switchbot/__init__.py", line 640, in open
    result = self._sendcommand(OPEN_KEY, self._retry_count)
  File "/usr/local/lib/python3.9/site-packages/switchbot/__init__.py", line 436, in _sendcommand
    return self._sendcommand(key, retry - 1)
  File "/usr/local/lib/python3.9/site-packages/switchbot/__init__.py", line 418, in _sendcommand
    notify_msg = self._readkey()
  File "/usr/local/lib/python3.9/site-packages/switchbot/__init__.py", line 386, in _readkey
    read_result: bytes = char.read()
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 197, in read
    return self.peripheral.readCharacteristic(self.valHandle)
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 530, in readCharacteristic
    resp = self._getResp('rd')
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 407, in _getResp
    resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
  File "/usr/local/lib/python3.9/site-packages/bluepy/btle.py", line 368, in _waitResp
    raise BTLEGattError("Bluetooth command failed", resp)
bluepy.btle.BTLEGattError: Bluetooth command failed (code: 2, error: Attribute can't be read)
```

**Comment by RenierM26** [comment] 2022-02-27 06:08
Hi @pascalwinters,

Does the curtain still operate when this error is logged?

**Comment by pascalwinters** [comment] 2022-02-27 07:22
> Hi @pascalwinters,
> 
> Does the curtain still operate when this error is logged?

Hi @RenierM26, yes the curtains are still operate. But before the second curtains are operate there is a big delay.

**Comment by pascalwinters** [comment] 2022-02-28 16:02
@RenierM26 I have just updated both SwitchBot pairs with new firmware v3.9. 
And with this new firmware also only the new SwitchBot’s are given an error. So it seems no firmware related issue. 
Any thoughts?

**Comment by RenierM26** [comment] 2022-02-28 16:42
Hi Pascal, did you log a support ticket for the firmware update? It would be easier to diagnose if I have a test device.

**Comment by RenierM26** [comment] 2022-02-28 16:43
I see they introduced firmware updates in the app. This will make it easier to find the issue

**Comment by pascalwinters** [comment] 2022-02-28 18:18
> I see they introduced firmware updates in the app. This will make it easier to find the issue

Yes, there was a firmware notification in the app. 
It was very helpful if we could add a extra log level for the raw messages so we can debug the communication. 
What’s your idea to reproduce the issue?

**Comment by RenierM26** [comment] 2022-03-01 05:11
Hi @pascalwinters,

I have updated my test bot and it operates without the attribute cannot be read issue. Could you perhaps provide some more background on your environment?

1) Is the device far away? (have you tried moving it closer? Just trying to determine if this is related to connectivity)
2) Any new Bluetooth devices introduced into the environment when the issue started to occur?
3) Performance/Silent mode?
4) Grouped via switchbot app?

These are just a few variable I can think of at the moment.

From your error, it looks like the API can't read notifications from the device. This hasn't changed in the latest firmware (at least not on my test device - ungrouped mode.)

I'm kind of in-between moving so I can't test grouped curtain bots at the moment. I only have access to a single curtain bot at the moment.

**Comment by pascalwinters** [comment] 2022-03-01 06:24
Hi @RenierM26,

1. Is the device far away? (have you tried moving it closer? Just trying to determine if this is related to connectivity)
    The device is maybe 1 mtr more far away than the other curtains with less walls between
2. Any new Bluetooth devices introduced into the environment when the issue started to occur?
   Only this new curtains
4. Performance/Silent mode?
   All Performance mode
6. Grouped via switchbot app?
   Both are grouped

> This hasn't changed in the latest firmware (at least not on my test device - ungrouped mode.)
How do you know this?

Can I see the raw messages? So I can compare the communication with the two sets.

**Comment by RenierM26** [comment] 2022-03-01 06:37
Reading notifications is a standard part of the Bluetooth stack. There could be an issue with the handle incorrectly calculated on grouped curtains. (There are two ways of doing this via the bluepy library)

My single test curtain bot doesn't log any error reading attributes messages. The bots return a success/failed/busy message after a command is sent and this is what the code reads. My plan was to use this in the future in the hassio integration.

I'll have a look at this later today after work. I'll need your assistance in testing this with grouped bots.

**Comment by pascalwinters** [comment] 2022-03-01 06:42
I'm happy to assistance. I can even test with a custom branch on your repo. So I you want to expand logging for example, we can test it. Let me know.

**Comment by pascalwinters** [comment] 2022-03-03 17:58
@RenierM26 did you had some time to test anything? Let me know when I can do anything.

**Comment by pascalwinters** [comment] 2022-03-10 17:27
@RenierM26 Any news, did you had time to test anything?

**Comment by pascalwinters** [comment] 2022-03-31 12:24
@RenierM26 Can I help or support you by testing or delivering some logs?

**Comment by ryingg** [comment] 2022-05-26 03:39
I also have the same error `Failed to call service cover/open_cover. Bluetooth command failed (code: 2, error: Attribute can't be read)` on my new Switchbot Curtains running firmware v3.3

**Comment by ninadpchaudhari** [comment] 2022-06-06 21:09
> @RenierM26 Can I help or support you by testing or delivering some logs?

Thank you for the enthusiasm, discussion & report. 
I have created PR #43 would you mind testing that branch? I do not have the exact configuration you have, but want to check if that patch solves the issue.
I'll be happy to help setup the development environment if you don't have much development experience.

<details>
<summary> Steps to test this python project, let me know If you need elaboration. </summary>

1. Ensure you have python3.9+ and git. 
2. execute : `pip3 uninstall pyswitchbot` < Removes existing pyswitchbot if installed. 
3. clone the repo: `git clone https://github.com/ninadpchaudhari/pySwitchbot.git && cd pySwitchbot ` 
4. Execute : `sudo python3` << Starts python with root prevlidges, in my system was required to access BLE
5. type in `from switchbot import GetSwitchbotDevices`
6. type in `print(GetSwitchbotDevices().discover())` < Do you see any output? if yes we can proceed ahead.
Don't post the output here ( might contain identifying information) , if you do see any output, just let me know. Thanks
</details>

**Comment by pascalwinters** [comment] 2022-06-08 12:28
> 

Hi, I'm happy to help. My development environment is running on Windows. 
When I try to run `from switchbot import GetSwitchbotDevices`  I'm getting an error: `ModuleNotFoundError: No module named 'bluepy'` 
I think bluepy is only for Linux 🤷‍♂️ 
I can test the integration in HomeAssistant with your PR later on. Does it make sense to add some debug logging to see what's going on and maybe to log some results?

**Comment by ninadpchaudhari** [comment] 2022-06-08 12:47
> > 
> 
> Hi, I'm happy to help. My development environment is running on Windows. When I try to run `from switchbot import GetSwitchbotDevices` I'm getting an error: `ModuleNotFoundError: No module named 'bluepy'` I think bluepy is only for Linux 🤷‍♂️ I can test the integration in HomeAssistant with your PR later on. Does it make sense to add some debug logging to see what's going on and maybe to log some results? 

Thank you again for getting back :) 
1. I just made a [custom component with the patched version](https://github.com/Switchbot-Python/switchbotPatched-Component) that way you can try it out on your RPI. Please let me know if you need help with installing custom components. i am still working on the documentation of that project. 
2. I think I have a fairly well understanding of the underlying bug ( I have described the same here https://github.com/Danielhiversen/pySwitchbot/issues/42 If you want to dive deep.)
3. I had to add a switch bot in my HA automation script and hence this new custom component was required. I am also planning to just create a new component which is based on the Manufacturer's provided implementation, you can [track the progress here](https://github.com/Switchbot-Python) if you are interested.

**Comment by pascalwinters** [comment] 2022-06-12 07:48
@ninadpchaudhari I'm running the switchbot integration in my HA instance right now on your git repo:
https://github.com/ninadpchaudhari/pySwitchbot

But I have the same issues.
`bluepy.btle.BTLEGattError: Bluetooth command failed (code: 2, error: Attribute can't be read)`

Maybe it's an idea to add some extra logging? So I can provide you more information? Every change in your master branch can I test now very quick.

**Comment by ninadpchaudhari** [comment] 2022-06-14 23:16
@pascalwinters  THank you again for your enthusiasm :) It keeps me going. 
1. You are right, I will add more logging into the component [patched switchbotPatched](https://github.com/Switchbot-Python/switchbotPatched-Component). I'll keep you posted here once it's done.
2. By that time, you try  [patched switchbotPatched](https://github.com/Switchbot-Python/switchbotPatched-Component) and see it works! The one you are referring to [this one](https://github.com/ninadpchaudhari/pySwitchbot) has the same name as the original one for which you need to add "Version:2.0" in the component setup.

**Comment by pascalwinters** [comment] 2022-06-15 06:33
@ninadpchaudhari Good to hear you're keep on going.
I hope we can fix the issue.
I'm, not using the patched component because I must disable or remove the current integration and my devices will also deleted.
So I choose to place the switchbot integration as custom component with the requirement part of the manifest changed to your repo, like this:
```
{
  "domain": "switchbot",
  "name": "SwitchBot",
  "documentation": "https://www.home-assistant.io/integrations/switchbot",
  "requirements": ["git+https://github.com/ninadpchaudhari/pySwitchbot.git@master#PySwitchbot==0.13.4"],
  "config_flow": true,
  "codeowners": ["@danielhiversen", "@RenierM26"],
  "iot_class": "local_polling",
  "loggers": ["switchbot"],
  "version": "1.0"
}
```
On this way it has no impact on my production HA environment and I can test very quick every change you will do in this branch. Switching to another branch for testing is also not an issue.
So I hope this will work for you too and we can fix the issue together on this way of work.

**Comment by RenierM26** [comment] 2022-06-16 10:21
Hi @pascalwinters and everyone else,

Would you guys mind testing the bleak version? It's fully async and bluepy (old bluetooth library) has a bunch of issues, fix one and another crops up.

https://github.com/RenierM26/ha-switchbot-curtain

**Comment by pascalwinters** [comment] 2022-06-16 18:34
> Hi @pascalwinters and everyone else,
> 
> Would you guys mind testing the bleak version? It's fully async and bluepy (old bluetooth library) has a bunch of issues, fix one and another crops up.
> 
> https://github.com/RenierM26/ha-switchbot-curtain

I see a lot of missing functionality, so what’s the main reason to swop to this integration? Because it’s not using bluepy?
The downside for my for testing is, my current entities won’t work anymore, so it’s breaking my production system. 
So I will test it, but for me i think it has too much impact. 

For me it should be a better solution to delete the bluespy dependency in the core SwitchBot integration of HA.

**Comment by ninadpchaudhari** [comment] 2022-06-16 23:02
> > Hi @pascalwinters and everyone else,
> > Would you guys mind testing the bleak version? It's fully async and bluepy (old bluetooth library) has a bunch of issues, fix one and another crops up.
> > https://github.com/RenierM26/ha-switchbot-curtain
> 
> I see a lot of missing functionality, so what’s the main reason to swop to this integration? Because it’s not using bluepy? The downside for my for testing is, my current entities won’t work anymore, so it’s breaking my production system. So I will test it, but for me i think it has too much impact.
> 
> For me it should be a better solution to delete the bluespy dependency in the core SwitchBot integration of HA.

@RenierM26  sincerely appreciates your efforts with the Bleak library. It is certainly an excellent library and a great move from bluepy.
The issue is, 
- Bleak is again another library that is supported by another individual. These libraries do help in making things cross-platform but it relies on 3rd party developer integrations. Which evident from bluepy does not always stick to the original principles. But again, Kudos to your work, that work can serve as an alternative for people trying to use the API on Windows.
- The issue with adding the async functions while keeping the function names the same is a major issue. We need to add additional functions which might add async functions while keeping the original functions. As @pascalwinters Mentioned it is certainly going to break some existing automation.
- I believe we need to follow the footsteps of the manufacturer and just use python3-bluz which is the official Linux package for Bluetooth ! I am making tiny progress here : https://github.com/Switchbot-Python Specially since HA does not support Windows anyways!

**Comment by RenierM26** [comment] 2022-06-17 05:56
Hi @ninadpchaudhari,

Had a look at python3-bluez, it's also busy fizzling out (https://github.com/pybluez/pybluez). It makes use of pybluez which is not under active development anymore.

Both pybluez and bluepy makes use of modified bluez versions that become to difficult to maintain. Bleak uses the built in bluez version (on linux based os) and doesn't modify it in any way, it's just a cli wrapper essentially.

**Comment by pascalwinters** [comment] 2022-06-22 19:43
> Hi @pascalwinters,
> 
> It's not a drop in replacement, the library is asynchronous and the functions need to be async. (Has the exact same functionality)
> 
> I have changed the official integration to work with async functions in this repo: https://github.com/RenierM26/ha-switchbot-curtain
> 
> Just change the domain name in the manifest.json file if you what to override the build in integration.
> 
> I'm planning on submitting a pull request on Hass when I get a chance. I have a few ideas to make it more efficient and responsive by using notification response instead of frequent active scans.

Ok. I will try to test it as soon as possible. Nice work making it async.

**Comment by ninadpchaudhari** [comment] 2022-06-22 22:44
> Hi @ninadpchaudhari,
> 
> Had a look at python3-bluez, it's also busy fizzling out (https://github.com/pybluez/pybluez). It makes use of pybluez which is not under active development anymore.
> 
> Both pybluez and bluepy makes use of modified bluez versions that become to difficult to maintain. Bleak uses the built in bluez version (on linux based os) and doesn't modify it in any way, it's just a cli wrapper essentially.

Let's continue that discussion on your PR. THat way we have this Issue only about the specified error. 
If we look at the Bleak Linux implementation, it still uses [TxDBus](https://github.com/cocagne/txdbus) which might be a supply-chain issue going down the road. Again it can be done and I am glad you are doing the bleak version, but I will be focusing on the native Bluez version back in my other version. Truly the beauty of Opensource indeed :) 

Also, my apologies, I wrongly typed pybluez, I meant only `bluez`.

**Comment by pascalwinters** [comment] 2022-06-24 16:08
> Hi @pascalwinters,
> 
> It's not a drop in replacement, the library is asynchronous and the functions need to be async. (Has the exact same functionality)
> 
> I have changed the official integration to work with async functions in this repo: https://github.com/RenierM26/ha-switchbot-curtain
> 
> Just change the domain name in the manifest.json file if you what to override the build in integration.
> 
> I'm planning on submitting a pull request on Hass when I get a chance. I have a few ideas to make it more efficient and responsive by using notification response instead of frequent active scans.

I did a test with this version, but I'm not getting this running up. My existing devices aren't available.
I see this messages in the HA log:
`Flow handler not found for entry Woonkamer for switchbot`

**Closed** 2022-07-21 14:29 UTC
